export const devices = [
  {
    "brand": "Google",
    "model": "Google Pixel 8 Pro",
    "price": 999,
    "color": ["Obsidian", "Porcelain", "Bay"],
    "storage": ["128GB", "256GB", "512GB", "1TB"],
    "images": ["google/pixel1.webp", "google/pixel2.webp", "google/pixel3.webp", "google/pixel4.webp"],
    "category": "smartphones",
    "screen": "6.7-inch LTPO OLED (120Hz)",
    "CPU": "Google Tensor G3",
    "numberOfCores": 9,
    "mainCamera": "50MP + 48MP + 48MP",
    "frontCamera": "10.5MP",
    "battery": "5050mAh (30W wired, 23W wireless)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 8",
    "price": 699,
    "color": ["Obsidian", "Hazel", "Rose", "Mint"],
    "storage": ["128GB", "256GB"],
    "images": ["google/pixel1.webp", "google/pixel2.webp", "google/pixel3.webp", "google/pixel4.webp"],
    "category": "smartphones",
    "screen": "6.2-inch OLED (120Hz)",
    "CPU": "Google Tensor G3",
    "numberOfCores": 9,
    "mainCamera": "50MP + 12MP",
    "frontCamera": "10.5MP",
    "battery": "4575mAh (27W wired, 18W wireless)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 7 Pro",
    "price": 899,
    "color": ["Obsidian", "Snow", "Hazel"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["google/pixel1.webp", "google/pixel2.webp", "google/pixel3.webp", "google/pixel4.webp"],
    "category": "smartphones",
    "screen": "6.7-inch LTPO OLED (120Hz)",
    "CPU": "Google Tensor G2",
    "numberOfCores": 8,
    "mainCamera": "50MP + 12MP + 48MP",
    "frontCamera": "10.8MP",
    "battery": "5000mAh (23W wired, 20W wireless)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 7",
    "price": 599,
    "color": ["Obsidian", "Snow", "Lemongrass"],
    "storage": ["128GB", "256GB"],
    "images": ["google/pixel1.webp", "google/pixel2.webp", "google/pixel3.webp", "google/pixel4.webp"],
    "category": "smartphones",
    "screen": "6.3-inch OLED (90Hz)",
    "CPU": "Google Tensor G2",
    "numberOfCores": 8,
    "mainCamera": "50MP + 12MP",
    "frontCamera": "10.8MP",
    "battery": "4355mAh (20W wired, 20W wireless)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 6 Pro",
    "price": 899,
    "color": ["Stormy Black", "Cloudy White", "Sorta Sunny"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["google/pixel1.webp", "google/pixel2.webp", "google/pixel3.webp", "google/pixel4.webp"],
    "category": "smartphones",
    "screen": "6.7-inch LTPO OLED (120Hz)",
    "CPU": "Google Tensor G1",
    "numberOfCores": 8,
    "mainCamera": "50MP + 12MP + 48MP",
    "frontCamera": "11.1MP",
    "battery": "5003mAh (23W wired, 20W wireless)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 6",
    "price": 599,
    "color": ["Stormy Black", "Sorta Seafoam", "Kinda Coral"],
    "storage": ["128GB", "256GB"],
    "images": ["google/pixel1.webp", "google/pixel2.webp", "google/pixel3.webp", "google/pixel4.webp"],
    "category": "smartphones",
    "screen": "6.4-inch OLED (90Hz)",
    "CPU": "Google Tensor G1",
    "numberOfCores": 8,
    "mainCamera": "50MP + 12MP",
    "frontCamera": "8MP",
    "battery": "4614mAh (21W wired, 20W wireless)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 5",
    "price": 699,
    "color": ["Just Black", "Sorta Sage"],
    "storage": ["128GB"],
    "images": ["google/pixelpro1.webp", "google/pixelpro2.webp", "google/pixelpro3.webp", "google/pixelpro4.webp"],
    "category": "smartphones",
    "screen": "6.0-inch OLED (90Hz)",
    "CPU": "Snapdragon 765G",
    "numberOfCores": 8,
    "mainCamera": "12.2MP + 16MP",
    "frontCamera": "8MP",
    "battery": "4080mAh (18W wired, 12W wireless)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 4a 5G",
    "price": 499,
    "color": ["Just Black", "Clearly White"],
    "storage": ["128GB"],
    "images": ["google/pixelpro1.webp", "google/pixelpro2.webp", "google/pixelpro3.webp", "google/pixelpro4.webp"],
    "category": "smartphones",
    "screen": "6.2-inch OLED (60Hz)",
    "CPU": "Snapdragon 765G",
    "numberOfCores": 8,
    "mainCamera": "12.2MP + 16MP",
    "frontCamera": "8MP",
    "battery": "3885mAh (18W wired)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 4 XL",
    "price": 899,
    "color": ["Clearly White", "Just Black", "Oh So Orange"],
    "storage": ["64GB", "128GB"],
    "images": ["google/pixelpro1.webp", "google/pixelpro2.webp", "google/pixelpro3.webp", "google/pixelpro4.webp"],
    "category": "smartphones",
    "screen": "6.3-inch OLED (90Hz)",
    "CPU": "Snapdragon 855",
    "numberOfCores": 8,
    "mainCamera": "12.2MP + 16MP",
    "frontCamera": "8MP + TOF",
    "battery": "3700mAh (18W wired, 10W wireless)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 4",
    "price": 799,
    "color": ["Clearly White", "Just Black", "Oh So Orange"],
    "storage": ["64GB", "128GB"],
    "images": ["google/pixelpro1.webp", "google/pixelpro2.webp", "google/pixelpro3.webp", "google/pixelpro4.webp"],
    "category": "smartphones",
    "screen": "5.7-inch OLED (90Hz)",
    "CPU": "Snapdragon 855",
    "numberOfCores": 8,
    "mainCamera": "12.2MP + 16MP",
    "frontCamera": "8MP + TOF",
    "battery": "2800mAh (18W wired, 10W wireless)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 7a",
    "price": 499,
    "color": ["Charcoal", "Snow", "Sea", "Coral"],
    "storage": ["128GB"],
    "images": ["google/pixelpro1.webp", "google/pixelpro2.webp", "google/pixelpro3.webp", "google/pixelpro4.webp"],
    "category": "smartphones",
    "screen": "6.1-inch OLED (90Hz)",
    "CPU": "Google Tensor G2",
    "numberOfCores": 8,
    "mainCamera": "64MP + 13MP",
    "frontCamera": "13MP",
    "battery": "4385mAh (18W wired, 7.5W wireless)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 6a",
    "price": 449,
    "color": ["Charcoal", "Chalk", "Sage"],
    "storage": ["128GB"],
    "images": ["google/pixel1.webp", "google/pixel2.webp", "google/pixel3.webp", "google/pixel4.webp"],
    "category": "smartphones",
    "screen": "6.1-inch OLED (60Hz)",
    "CPU": "Google Tensor G1",
    "numberOfCores": 8,
    "mainCamera": "12.2MP + 12MP",
    "frontCamera": "8MP",
    "battery": "4410mAh (18W wired)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 5a",
    "price": 449,
    "color": ["Mostly Black"],
    "storage": ["128GB"],
    "images": ["google/pixel1.webp", "google/pixel2.webp", "google/pixel3.webp", "google/pixel4.webp"],
    "category": "smartphones",
    "screen": "6.34-inch OLED (60Hz)",
    "CPU": "Snapdragon 765G",
    "numberOfCores": 8,
    "mainCamera": "12.2MP + 16MP",
    "frontCamera": "8MP",
    "battery": "4680mAh (18W wired)"
  },
  {
    "brand": "Google",
    "model": "Google Pixel 4a",
    "price": 349,
    "color": ["Just Black"],
    "storage": ["128GB"],
    "images": ["google/pixel1.webp", "google/pixel2.webp", "google/pixel3.webp", "google/pixel4.webp"],
    "category": "smartphones",
    "screen": "5.81-inch OLED (60Hz)",
    "CPU": "Snapdragon 730G",
    "numberOfCores": 8,
    "mainCamera": "12.2MP",
    "frontCamera": "8MP",
    "battery": "3140mAh (18W wired)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi 14 Pro",
    "price": 999,
    "color": ["Black", "White", "Green", "Pink"],
    "storage": ["256GB", "512GB", "1TB"],
    "images": ["xiaomi/xiaomi141.webp", "xiaomi/xiaomi142.webp", "xiaomi/xiaomi143.webp", "xiaomi/xiaomi144.webp"],
    "category": "smartphones",
    "screen": "6.73-inch LTPO AMOLED (120Hz)",
    "CPU": "Snapdragon 8 Gen 3",
    "numberOfCores": 8,
    "mainCamera": "50MP (Leica) + 50MP + 50MP",
    "frontCamera": "32MP",
    "battery": "4880mAh (120W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi 14",
    "price": 799,
    "color": ["Black", "White", "Jade Green"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["xiaomi/xiaomi141.webp", "xiaomi/xiaomi142.webp", "xiaomi/xiaomi143.webp", "xiaomi/xiaomi144.webp"],
    "category": "smartphones",
    "screen": "6.36-inch AMOLED (120Hz)",
    "CPU": "Snapdragon 8 Gen 3",
    "numberOfCores": 8,
    "mainCamera": "50MP (Leica) + 50MP + 50MP",
    "frontCamera": "32MP",
    "battery": "4610mAh (90W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi 13 Ultra",
    "price": 1299,
    "color": ["Black", "Green", "White"],
    "storage": ["256GB", "512GB", "1TB"],
    "images": ["xiaomi/xiaomi141.webp", "xiaomi/xiaomi142.webp", "xiaomi/xiaomi143.webp", "xiaomi/xiaomi144.webp"],
    "category": "smartphones",
    "screen": "6.73-inch LTPO AMOLED (120Hz)",
    "CPU": "Snapdragon 8 Gen 2",
    "numberOfCores": 8,
    "mainCamera": "50MP (Leica) + 50MP + 50MP + 50MP",
    "frontCamera": "32MP",
    "battery": "5000mAh (90W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi 13 Pro",
    "price": 999,
    "color": ["Ceramic Black", "Ceramic White", "Sky Blue"],
    "storage": ["256GB", "512GB"],
    "images": ["xiaomi/xiaomi141.webp", "xiaomi/xiaomi142.webp", "xiaomi/xiaomi143.webp", "xiaomi/xiaomi144.webp"],
    "category": "smartphones",
    "screen": "6.73-inch LTPO AMOLED (120Hz)",
    "CPU": "Snapdragon 8 Gen 2",
    "numberOfCores": 8,
    "mainCamera": "50MP (Leica) + 50MP + 50MP",
    "frontCamera": "32MP",
    "battery": "4820mAh (120W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi 13",
    "price": 699,
    "color": ["Black", "White", "Flora Green", "Mountain Blue"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["xiaomi/xiaomi141.webp", "xiaomi/xiaomi142.webp", "xiaomi/xiaomi143.webp", "xiaomi/xiaomi144.webp"],
    "category": "smartphones",
    "screen": "6.36-inch AMOLED (120Hz)",
    "CPU": "Snapdragon 8 Gen 2",
    "numberOfCores": 8,
    "mainCamera": "50MP (Leica) + 12MP + 10MP",
    "frontCamera": "32MP",
    "battery": "4500mAh (67W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi 12S Ultra",
    "price": 1199,
    "color": ["Black", "Dark Green"],
    "storage": ["256GB", "512GB"],
    "images": ["xiaomi/xiaomi141.webp", "xiaomi/xiaomi142.webp", "xiaomi/xiaomi143.webp", "xiaomi/xiaomi144.webp"],
    "category": "smartphones",
    "screen": "6.73-inch AMOLED (120Hz)",
    "CPU": "Snapdragon 8+ Gen 1",
    "numberOfCores": 8,
    "mainCamera": "50MP (Leica) + 48MP + 48MP",
    "frontCamera": "32MP",
    "battery": "4860mAh (67W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi 12 Pro",
    "price": 899,
    "color": ["Gray", "Blue", "Purple", "Green"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["xiaomi/xiaomi141.webp", "xiaomi/xiaomi142.webp", "xiaomi/xiaomi143.webp", "xiaomi/xiaomi144.webp"],
    "category": "smartphones",
    "screen": "6.73-inch LTPO AMOLED (120Hz)",
    "CPU": "Snapdragon 8 Gen 1",
    "numberOfCores": 8,
    "mainCamera": "50MP + 50MP + 50MP",
    "frontCamera": "32MP",
    "battery": "4600mAh (120W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi 12",
    "price": 699,
    "color": ["Black", "Blue", "Purple", "Green"],
    "storage": ["128GB", "256GB"],
    "images": ["xiaomi/xiaomi141.webp", "xiaomi/xiaomi142.webp", "xiaomi/xiaomi143.webp", "xiaomi/xiaomi144.webp"],
    "category": "smartphones",
    "screen": "6.28-inch AMOLED (120Hz)",
    "CPU": "Snapdragon 8 Gen 1",
    "numberOfCores": 8,
    "mainCamera": "50MP + 13MP + 5MP",
    "frontCamera": "32MP",
    "battery": "4500mAh (67W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi 11 Ultra",
    "price": 1199,
    "color": ["Ceramic Black", "Ceramic White"],
    "storage": ["256GB", "512GB"],
    "images": ["xiaomi/xiaomi141.webp", "xiaomi/xiaomi142.webp", "xiaomi/xiaomi143.webp", "xiaomi/xiaomi144.webp"],
    "category": "smartphones",
    "screen": "6.81-inch AMOLED (120Hz)",
    "CPU": "Snapdragon 888",
    "numberOfCores": 8,
    "mainCamera": "50MP + 48MP + 48MP",
    "frontCamera": "20MP",
    "battery": "5000mAh (67W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi 11T Pro",
    "price": 649,
    "color": ["Meteorite Gray", "Moonlight White", "Celestial Blue"],
    "storage": ["128GB", "256GB"],
    "images": ["xiaomi/xiaomi131.webp", "xiaomi/xiaomi132.webp", "xiaomi/xiaomi133.webp", "xiaomi/xiaomi134.webp"],
    "category": "smartphones",
    "screen": "6.67-inch AMOLED (120Hz)",
    "CPU": "Snapdragon 888",
    "numberOfCores": 8,
    "mainCamera": "108MP + 8MP + 5MP",
    "frontCamera": "16MP",
    "battery": "5000mAh (120W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi 11 Lite 5G NE",
    "price": 349,
    "color": ["Truffle Black", "Bubblegum Blue", "Peach Pink", "Snowflake White"],
    "storage": ["64GB", "128GB", "256GB"],
    "images": ["xiaomi/xiaomi131.webp", "xiaomi/xiaomi132.webp", "xiaomi/xiaomi133.webp", "xiaomi/xiaomi134.webp"],
    "category": "smartphones",
    "screen": "6.55-inch AMOLED (90Hz)",
    "CPU": "Snapdragon 778G",
    "numberOfCores": 8,
    "mainCamera": "64MP + 8MP + 5MP",
    "frontCamera": "20MP",
    "battery": "4250mAh (33W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi Redmi Note 13 Pro+",
    "price": 399,
    "color": ["Midnight Black", "Aurora Purple", "Glacier Blue"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["xiaomi/xiaomi131.webp", "xiaomi/xiaomi132.webp", "xiaomi/xiaomi133.webp", "xiaomi/xiaomi134.webp"],
    "category": "smartphones",
    "screen": "6.67-inch AMOLED (120Hz)",
    "CPU": "Dimensity 7200 Ultra",
    "numberOfCores": 8,
    "mainCamera": "200MP + 8MP + 2MP",
    "frontCamera": "16MP",
    "battery": "5000mAh (120W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi Redmi Note 13 Pro",
    "price": 299,
    "color": ["Black", "Blue", "Purple", "White"],
    "storage": ["128GB", "256GB"],
    "images": ["xiaomi/xiaomi131.webp", "xiaomi/xiaomi132.webp", "xiaomi/xiaomi133.webp", "xiaomi/xiaomi134.webp"],
    "category": "smartphones",
    "screen": "6.67-inch AMOLED (120Hz)",
    "CPU": "Snapdragon 7s Gen 2",
    "numberOfCores": 8,
    "mainCamera": "200MP + 8MP + 2MP",
    "frontCamera": "16MP",
    "battery": "5100mAh (67W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi Redmi Note 12 Pro 5G",
    "price": 249,
    "color": ["Onyx Gray", "Glacier Blue", "Polar White"],
    "storage": ["128GB", "256GB"],
    "images": ["xiaomi/xiaomi131.webp", "xiaomi/xiaomi132.webp", "xiaomi/xiaomi133.webp", "xiaomi/xiaomi134.webp"],
    "category": "smartphones",
    "screen": "6.67-inch AMOLED (120Hz)",
    "CPU": "Dimensity 1080",
    "numberOfCores": 8,
    "mainCamera": "50MP + 8MP + 2MP",
    "frontCamera": "16MP",
    "battery": "5000mAh (67W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi Redmi K70 Pro",
    "price": 599,
    "color": ["Black", "White", "Blue", "Purple"],
    "storage": ["256GB", "512GB", "1TB"],
    "images": ["xiaomi/xiaomi131.webp", "xiaomi/xiaomi132.webp", "xiaomi/xiaomi133.webp", "xiaomi/xiaomi134.webp"],
    "category": "smartphones",
    "screen": "6.67-inch AMOLED (120Hz)",
    "CPU": "Snapdragon 8 Gen 3",
    "numberOfCores": 8,
    "mainCamera": "50MP + 50MP + 12MP",
    "frontCamera": "16MP",
    "battery": "5000mAh (120W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi Redmi K60 Ultra",
    "price": 499,
    "color": ["Black", "White", "Green"],
    "storage": ["256GB", "512GB", "1TB"],
    "images": ["xiaomi/xiaomi131.webp", "xiaomi/xiaomi132.webp", "xiaomi/xiaomi133.webp", "xiaomi/xiaomi134.webp"],
    "category": "smartphones",
    "screen": "6.67-inch AMOLED (144Hz)",
    "CPU": "Dimensity 9200+",
    "numberOfCores": 8,
    "mainCamera": "50MP + 8MP + 2MP",
    "frontCamera": "20MP",
    "battery": "5000mAh (120W fast charging)"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi Redmi 12 5G",
    "price": 199,
    "color": ["Moonstone Silver", "Jade Black", "Polar Blue"],
    "storage": ["64GB", "128GB"],
    "images": ["xiaomi/xiaomi131.webp", "xiaomi/xiaomi132.webp", "xiaomi/xiaomi133.webp", "xiaomi/xiaomi134.webp"],
    "category": "smartphones",
    "screen": "6.79-inch IPS LCD (90Hz)",
    "CPU": "Snapdragon 4 Gen 2",
    "numberOfCores": 8,
    "mainCamera": "50MP + 2MP",
    "frontCamera": "8MP",
    "battery": "5000mAh (18W fast charging)"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 16 Pro",
    "price": 1099,
    "color": ["Space Black", "Silver", "Gold", "Deep Purple"],
    "storage": ["128GB", "256GB", "512GB", "1TB"],
    "images": ["iPhones/iphone161.webp", "iPhones/iphone162.webp", "iPhones/iphone163.webp", "iPhones/iphone164.webp"],
    "category": "smartphones",
    "screen": "6.7-inch Super Retina XDR",
    "CPU": "A18 Pro",
    "numberOfCores": 6,
    "mainCamera": "48MP + 12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "4422mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 16 Plus",
    "price": 999,
    "color": ["Midnight", "Starlight", "Blue", "Purple", "Red"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["iPhones/iphone161.webp", "iPhones/iphone162.webp", "iPhones/iphone163.webp", "iPhones/iphone164.webp"],
    "category": "smartphones",
    "screen": "6.7-inch Super Retina XDR",
    "CPU": "A18",
    "numberOfCores": 6,
    "mainCamera": "48MP + 12MP",
    "frontCamera": "12MP",
    "battery": "4325mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 16",
    "price": 899,
    "color": ["Midnight", "Starlight", "Blue", "Purple", "Red"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["iPhones/iphone161.webp", "iPhones/iphone162.webp", "iPhones/iphone163.webp", "iPhones/iphone164.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Super Retina XDR",
    "CPU": "A18",
    "numberOfCores": 6,
    "mainCamera": "48MP + 12MP",
    "frontCamera": "12MP",
    "battery": "4000mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 15 Pro Max",
    "price": 1199,
    "color": ["Space Black", "Silver", "Gold", "Deep Blue"],
    "storage": ["256GB", "512GB", "1TB"],
    "images": ["iPhones/iphone1.webp", "iPhones/iphone2.webp", "iPhones/iphone3.webp", "iPhones/iphone4.webp"],
    "category": "smartphones",
    "screen": "6.7-inch Super Retina XDR",
    "CPU": "A17 Pro",
    "numberOfCores": 6,
    "mainCamera": "48MP + 12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "4422mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 15 Pro",
    "price": 999,
    "color": ["Space Black", "Silver", "Gold", "Deep Blue"],
    "storage": ["128GB", "256GB", "512GB", "1TB"],
    "images": ["iPhones/iphone1.webp", "iPhones/iphone2.webp", "iPhones/iphone3.webp", "iPhones/iphone4.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Super Retina XDR",
    "CPU": "A17 Pro",
    "numberOfCores": 6,
    "mainCamera": "48MP + 12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "3274mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 15 Plus",
    "price": 899,
    "color": ["Black", "White", "Blue", "Pink", "Yellow"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["iPhones/iphone1.webp", "iPhones/iphone2.webp", "iPhones/iphone3.webp", "iPhones/iphone4.webp"],
    "category": "smartphones",
    "screen": "6.7-inch Super Retina XDR",
    "CPU": "A16 Bionic",
    "numberOfCores": 6,
    "mainCamera": "48MP + 12MP",
    "frontCamera": "12MP",
    "battery": "4383mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 15",
    "price": 799,
    "color": ["Black", "White", "Blue", "Pink", "Yellow"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["iPhones/iphone1.webp", "iPhones/iphone2.webp", "iPhones/iphone3.webp", "iPhones/iphone4.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Super Retina XDR",
    "CPU": "A16 Bionic",
    "numberOfCores": 6,
    "mainCamera": "48MP + 12MP",
    "frontCamera": "12MP",
    "battery": "3349mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 14 Pro Max",
    "price": 1099,
    "color": ["Space Black", "Silver", "Gold", "Deep Purple"],
    "storage": ["128GB", "256GB", "512GB", "1TB"],
    "images": ["iPhones/iphone41.webp", "iPhones/iphone42.webp", "iPhones/iphone43.webp", "iPhones/iphone44.webp"],
    "category": "smartphones",
    "screen": "6.7-inch Super Retina XDR",
    "CPU": "A16 Bionic",
    "numberOfCores": 6,
    "mainCamera": "48MP + 12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "4323mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 14 Pro",
    "price": 999,
    "color": ["Space Black", "Silver", "Gold", "Deep Purple"],
    "storage": ["128GB", "256GB", "512GB", "1TB"],
    "images": ["iPhones/iphone41.webp", "iPhones/iphone42.webp", "iPhones/iphone43.webp", "iPhones/iphone44.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Super Retina XDR",
    "CPU": "A16 Bionic",
    "numberOfCores": 6,
    "mainCamera": "48MP + 12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "3200mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 14 Plus",
    "price": 899,
    "color": ["Midnight", "Starlight", "Blue", "Purple", "Red"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["iPhones/iphone41.webp", "iPhones/iphone42.webp", "iPhones/iphone43.webp", "iPhones/iphone44.webp"],
    "category": "smartphones",
    "screen": "6.7-inch Super Retina XDR",
    "CPU": "A15 Bionic",
    "numberOfCores": 6,
    "mainCamera": "12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "4325mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 14",
    "price": 799,
    "color": ["Midnight", "Starlight", "Blue", "Purple", "Red"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["iPhones/iphone41.webp", "iPhones/iphone42.webp", "iPhones/iphone43.webp", "iPhones/iphone44.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Super Retina XDR",
    "CPU": "A15 Bionic",
    "numberOfCores": 6,
    "mainCamera": "12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "3279mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 13 Pro Max",
    "price": 1099,
    "color": ["Graphite", "Silver", "Gold", "Sierra Blue"],
    "storage": ["128GB", "256GB", "512GB", "1TB"],
    "images": ["iPhones/iphone41.webp", "iPhones/iphone42.webp", "iPhones/iphone43.webp", "iPhones/iphone44.webp"],
    "category": "smartphones",
    "screen": "6.7-inch Super Retina XDR",
    "CPU": "A15 Bionic",
    "numberOfCores": 6,
    "mainCamera": "12MP + 12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "4352mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 13 Pro",
    "price": 999,
    "color": ["Graphite", "Silver", "Gold", "Sierra Blue"],
    "storage": ["128GB", "256GB", "512GB", "1TB"],
    "images": ["iPhones/iphone41.webp", "iPhones/iphone42.webp", "iPhones/iphone43.webp", "iPhones/iphone44.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Super Retina XDR",
    "CPU": "A15 Bionic",
    "numberOfCores": 6,
    "mainCamera": "12MP + 12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "3095mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 13",
    "price": 799,
    "color": ["Pink", "Blue", "Midnight", "Starlight", "Red"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["iPhones/iphone41.webp", "iPhones/iphone42.webp", "iPhones/iphone43.webp", "iPhones/iphone44.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Super Retina XDR",
    "CPU": "A15 Bionic",
    "numberOfCores": 6,
    "mainCamera": "12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "3227mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 12 Pro Max",
    "price": 1099,
    "color": ["Graphite", "Silver", "Gold", "Pacific Blue"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["iPhones/iphone1.webp", "iPhones/iphone2.webp", "iPhones/iphone3.webp", "iPhones/iphone4.webp"],
    "category": "smartphones",
    "screen": "6.7-inch Super Retina XDR",
    "CPU": "A14 Bionic",
    "numberOfCores": 6,
    "mainCamera": "12MP + 12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "3687mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 12 Pro",
    "price": 999,
    "color": ["Graphite", "Silver", "Gold", "Pacific Blue"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["iPhones/iphone1.webp", "iPhones/iphone2.webp", "iPhones/iphone3.webp", "iPhones/iphone4.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Super Retina XDR",
    "CPU": "A14 Bionic",
    "numberOfCores": 6,
    "mainCamera": "12MP + 12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "2815mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 12",
    "price": 699,
    "color": ["Black", "White", "Blue", "Green", "Red"],
    "storage": ["64GB", "128GB", "256GB"],
    "images": ["iPhones/iphone1.webp", "iPhones/iphone2.webp", "iPhones/iphone3.webp", "iPhones/iphone4.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Super Retina XDR",
    "CPU": "A14 Bionic",
    "numberOfCores": 6,
    "mainCamera": "12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "2815mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 11 Pro Max",
    "price": 1099,
    "color": ["Space Gray", "Silver", "Gold", "Midnight Green"],
    "storage": ["64GB", "256GB", "512GB"],
    "images": ["iPhones/iphone1.webp", "iPhones/iphone2.webp", "iPhones/iphone3.webp", "iPhones/iphone4.webp"],
    "category": "smartphones",
    "screen": "6.5-inch Super Retina XDR",
    "CPU": "A13 Bionic",
    "numberOfCores": 6,
    "mainCamera": "12MP + 12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "3969mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 11 Pro",
    "price": 999,
    "color": ["Space Gray", "Silver", "Gold", "Midnight Green"],
    "storage": ["64GB", "256GB", "512GB"],
    "images": ["iPhones/iphone1.webp", "iPhones/iphone2.webp", "iPhones/iphone3.webp", "iPhones/iphone4.webp"],
    "category": "smartphones",
    "screen": "5.8-inch Super Retina XDR",
    "CPU": "A13 Bionic",
    "numberOfCores": 6,
    "mainCamera": "12MP + 12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "3046mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple iPhone 11",
    "price": 699,
    "color": ["Black", "White", "Green", "Yellow", "Purple", "Red"],
    "storage": ["64GB", "128GB", "256GB"],
    "images": ["iPhones/iphone1.webp", "iPhones/iphone2.webp", "iPhones/iphone3.webp", "iPhones/iphone4.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Liquid Retina HD",
    "CPU": "A13 Bionic",
    "numberOfCores": 6,
    "mainCamera": "12MP + 12MP",
    "frontCamera": "12MP",
    "battery": "3110mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S24 Ultra",
    "price": 1299,
    "color": ["Titanium Black", "Titanium Gray", "Titanium Violet", "Titanium Yellow"],
    "storage": ["256GB", "512GB", "1TB"],
    "images": ["samsung/samsung1.webp", "samsung/samsung2.webp", "samsung/samsung3.webp", "samsung/samsung4.webp"],
    "category": "smartphones",
    "screen": "6.8-inch Dynamic AMOLED 2X",
    "CPU": "Snapdragon 8 Gen 3",
    "numberOfCores": 8,
    "mainCamera": "200MP + 50MP + 12MP + 10MP",
    "frontCamera": "12MP",
    "battery": "5000mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S24+",
    "price": 999,
    "color": ["Onyx Black", "Marble Gray", "Cobalt Violet", "Amber Yellow"],
    "storage": ["256GB", "512GB"],
    "images": ["samsung/samsung1.webp", "samsung/samsung2.webp", "samsung/samsung3.webp", "samsung/samsung4.webp"],
    "category": "smartphones",
    "screen": "6.7-inch Dynamic AMOLED 2X",
    "CPU": "Snapdragon 8 Gen 3",
    "numberOfCores": 8,
    "mainCamera": "50MP + 12MP + 10MP",
    "frontCamera": "12MP",
    "battery": "4900mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S24",
    "price": 799,
    "color": ["Onyx Black", "Marble Gray", "Cobalt Violet", "Amber Yellow"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["samsung/samsung1.webp", "samsung/samsung2.webp", "samsung/samsung3.webp", "samsung/samsung4.webp"],
    "category": "smartphones",
    "screen": "6.2-inch Dynamic AMOLED 2X",
    "CPU": "Snapdragon 8 Gen 3",
    "numberOfCores": 8,
    "mainCamera": "50MP + 12MP + 10MP",
    "frontCamera": "12MP",
    "battery": "4000mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S23 Ultra",
    "price": 1199,
    "color": ["Phantom Black", "Cream", "Green", "Lavender"],
    "storage": ["256GB", "512GB", "1TB"],
    "images": ["samsung/samsung1.webp", "samsung/samsung2.webp", "samsung/samsung3.webp", "samsung/samsung4.webp"],
    "category": "smartphones",
    "screen": "6.8-inch Dynamic AMOLED 2X",
    "CPU": "Snapdragon 8 Gen 2",
    "numberOfCores": 8,
    "mainCamera": "200MP + 12MP + 10MP + 10MP",
    "frontCamera": "12MP",
    "battery": "5000mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S23+",
    "price": 999,
    "color": ["Phantom Black", "Cream", "Green", "Lavender"],
    "storage": ["256GB", "512GB"],
    "images": ["samsung/samsung1.webp", "samsung/samsung2.webp", "samsung/samsung3.webp", "samsung/samsung4.webp"],
    "category": "smartphones",
    "screen": "6.6-inch Dynamic AMOLED 2X",
    "CPU": "Snapdragon 8 Gen 2",
    "numberOfCores": 8,
    "mainCamera": "50MP + 12MP + 10MP",
    "frontCamera": "12MP",
    "battery": "4700mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S23",
    "price": 799,
    "color": ["Phantom Black", "Cream", "Green", "Lavender"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["samsung/samsung1.webp", "samsung/samsung2.webp", "samsung/samsung3.webp", "samsung/samsung4.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Dynamic AMOLED 2X",
    "CPU": "Snapdragon 8 Gen 2",
    "numberOfCores": 8,
    "mainCamera": "50MP + 12MP + 10MP",
    "frontCamera": "12MP",
    "battery": "3900mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S22 Ultra",
    "price": 1199,
    "color": ["Phantom Black", "White", "Burgundy", "Green"],
    "storage": ["128GB", "256GB", "512GB", "1TB"],
    "images": ["samsung/samsung241.webp", "samsung/samsung242.webp", "samsung/samsung243.webp", "samsung/samsung244.webp"],
    "category": "smartphones",
    "screen": "6.8-inch Dynamic AMOLED 2X",
    "CPU": "Snapdragon 8 Gen 1",
    "numberOfCores": 8,
    "mainCamera": "108MP + 12MP + 10MP + 10MP",
    "frontCamera": "40MP",
    "battery": "5000mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S22+",
    "price": 999,
    "color": ["Phantom Black", "White", "Pink Gold", "Green"],
    "storage": ["128GB", "256GB"],
    "images": ["samsung/samsung241.webp", "samsung/samsung242.webp", "samsung/samsung243.webp", "samsung/samsung244.webp"],
    "category": "smartphones",
    "screen": "6.6-inch Dynamic AMOLED 2X",
    "CPU": "Snapdragon 8 Gen 1",
    "numberOfCores": 8,
    "mainCamera": "50MP + 12MP + 10MP",
    "frontCamera": "10MP",
    "battery": "4500mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S22",
    "price": 799,
    "color": ["Phantom Black", "White", "Pink Gold", "Green"],
    "storage": ["128GB", "256GB"],
    "images": ["samsung/samsung241.webp", "samsung/samsung242.webp", "samsung/samsung243.webp", "samsung/samsung244.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Dynamic AMOLED 2X",
    "CPU": "Snapdragon 8 Gen 1",
    "numberOfCores": 8,
    "mainCamera": "50MP + 12MP + 10MP",
    "frontCamera": "10MP",
    "battery": "3700mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S21 Ultra",
    "price": 1199,
    "color": ["Phantom Black", "Silver", "Titanium", "Navy"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["samsung/samsung241.webp", "samsung/samsung242.webp", "samsung/samsung243.webp", "samsung/samsung244.webp"],
    "category": "smartphones",
    "screen": "6.8-inch Dynamic AMOLED 2X",
    "CPU": "Exynos 2100/Snapdragon 888",
    "numberOfCores": 8,
    "mainCamera": "108MP + 12MP + 10MP + 10MP",
    "frontCamera": "40MP",
    "battery": "5000mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S21+",
    "price": 999,
    "color": ["Phantom Black", "Silver", "Violet", "Pink"],
    "storage": ["128GB", "256GB"],
    "images": ["samsung/samsung241.webp", "samsung/samsung242.webp", "samsung/samsung243.webp", "samsung/samsung244.webp"],
    "category": "smartphones",
    "screen": "6.7-inch Dynamic AMOLED 2X",
    "CPU": "Exynos 2100/Snapdragon 888",
    "numberOfCores": 8,
    "mainCamera": "12MP + 12MP + 64MP",
    "frontCamera": "10MP",
    "battery": "4800mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S21",
    "price": 799,
    "color": ["Phantom Black", "Silver", "Violet", "Pink"],
    "storage": ["128GB", "256GB"],
    "images": ["samsung/samsung241.webp", "samsung/samsung242.webp", "samsung/samsung243.webp", "samsung/samsung244.webp"],
    "category": "smartphones",
    "screen": "6.2-inch Dynamic AMOLED 2X",
    "CPU": "Exynos 2100/Snapdragon 888",
    "numberOfCores": 8,
    "mainCamera": "12MP + 12MP + 64MP",
    "frontCamera": "10MP",
    "battery": "4000mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S20 Ultra",
    "price": 1399,
    "color": ["Cosmic Black", "Cosmic Gray"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["samsung/samsung241.webp", "samsung/samsung242.webp", "samsung/samsung243.webp", "samsung/samsung244.webp"],
    "category": "smartphones",
    "screen": "6.9-inch Dynamic AMOLED 2X",
    "CPU": "Exynos 990/Snapdragon 865",
    "numberOfCores": 8,
    "mainCamera": "108MP + 48MP + 12MP + DepthVision",
    "frontCamera": "40MP",
    "battery": "5000mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S20+",
    "price": 1199,
    "color": ["Cosmic Black", "Cosmic Gray", "Cloud Blue", "Cloud White"],
    "storage": ["128GB", "256GB", "512GB"],
    "images": ["samsung/samsung241.webp", "samsung/samsung242.webp", "samsung/samsung243.webp", "samsung/samsung244.webp"],
    "category": "smartphones",
    "screen": "6.7-inch Dynamic AMOLED 2X",
    "CPU": "Exynos 990/Snapdragon 865",
    "numberOfCores": 8,
    "mainCamera": "12MP + 64MP + 12MP + DepthVision",
    "frontCamera": "10MP",
    "battery": "4500mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S20",
    "price": 999,
    "color": ["Cosmic Black", "Cosmic Gray", "Cloud Blue", "Cloud White"],
    "storage": ["128GB", "256GB"],
    "images": ["samsung/samsung241.webp", "samsung/samsung242.webp", "samsung/samsung243.webp", "samsung/samsung244.webp"],
    "category": "smartphones",
    "screen": "6.2-inch Dynamic AMOLED 2X",
    "CPU": "Exynos 990/Snapdragon 865",
    "numberOfCores": 8,
    "mainCamera": "12MP + 64MP + 12MP",
    "frontCamera": "10MP",
    "battery": "4000mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S10+",
    "price": 999,
    "color": ["Prism Black", "Prism White", "Prism Blue", "Prism Green"],
    "storage": ["128GB", "512GB", "1TB"],
    "images": ["samsung/samsung101.webp", "samsung/amsung102.webp", "samsung/samsung103.webp", "samsung/samsung104.webp"],
    "category": "smartphones",
    "screen": "6.4-inch Dynamic AMOLED",
    "CPU": "Exynos 9820/Snapdragon 855",
    "numberOfCores": 8,
    "mainCamera": "12MP + 12MP + 16MP",
    "frontCamera": "10MP + 8MP",
    "battery": "4100mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S10",
    "price": 899,
    "color": ["Prism Black", "Prism White", "Prism Blue", "Prism Green"],
    "storage": ["128GB", "512GB"],
    "images": ["samsung/samsung101.webp", "samsung/samsung102.webp", "samsung/samsung103.webp", "samsung/samsung104.webp"],
    "category": "smartphones",
    "screen": "6.1-inch Dynamic AMOLED",
    "CPU": "Exynos 9820/Snapdragon 855",
    "numberOfCores": 8,
    "mainCamera": "12MP + 12MP + 16MP",
    "frontCamera": "10MP",
    "battery": "3400mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy S10e",
    "price": 749,
    "color": ["Prism Black", "Prism White", "Prism Blue", "Prism Green"],
    "storage": ["128GB", "256GB"],
    "images": ["samsung/samsung101.webp", "samsung/samsung102.webp", "samsung/samsung103.webp", "samsung/samsung104.webp"],
    "category": "smartphones",
    "screen": "5.8-inch Dynamic AMOLED",
    "CPU": "Exynos 9820/Snapdragon 855",
    "numberOfCores": 8,
    "mainCamera": "12MP + 16MP",
    "frontCamera": "10MP",
    "battery": "3100mAh"
  },
  {
    "brand": "Huawei",
    "model": "Huawei P50 Pro",
    "price": 999,
    "color": ["Golden Black", "Cocoa Gold"],
    "storage": ["128GB", "256GB"],
    "images": ["huawei/huawei91.webp", "huawei/huawei92.webp", "huawei/huawei93.webp", "huawei/huawei94.webp"],
    "category": "smartphones",
    "screen": "6.6-inch OLED (120Hz)",
    "CPU": "Kirin 9000",
    "numberOfCores": 8,
    "mainCamera": "50MP + 64MP + 13MP",
    "frontCamera": "13MP",
    "battery": "4360mAh (66W wired)"
  },
  {
    "brand": "Huawei",
    "model": "Huawei Mate 40 Pro",
    "price": 1199,
    "color": ["Mystic Silver", "Black"],
    "storage": ["256GB", "512GB"],
    "images": ["huawei/huawei1.webp", "huawei/huawei2.webp", "huawei/huawei3.webp", "huawei/huawei4.webp"],
    "category": "smartphones",
    "screen": "6.76-inch OLED (90Hz)",
    "CPU": "Kirin 9000",
    "numberOfCores": 8,
    "mainCamera": "50MP + 20MP + 12MP",
    "frontCamera": "13MP",
    "battery": "4400mAh (66W wired)"
  },
  {
    "brand": "Huawei",
    "model": "Huawei Nova 9",
    "price": 499,
    "color": ["Starry Blue", "Black"],
    "storage": ["128GB"],
    "images": ["huawei/huawei91.webp", "huawei/huawei92.webp", "huawei/huawei93.webp", "huawei/huawei94.webp"],
    "category": "smartphones",
    "screen": "6.57-inch OLED (120Hz)",
    "CPU": "Snapdragon 778G",
    "numberOfCores": 8,
    "mainCamera": "50MP + 8MP + 2MP + 2MP",
    "frontCamera": "32MP",
    "battery": "4300mAh (66W wired)"
  },
  {
    "brand": "Huawei",
    "model": "Huawei P Smart 2021",
    "price": 249,
    "color": ["Midnight Black", "Crush Green"],
    "storage": ["64GB", "128GB"],
    "images": ["huawei/huawei1.webp", "huawei/huawei2.webp", "huawei/huawei3.webp", "huawei/huawei4.webp"],
    "category": "smartphones",
    "screen": "6.67-inch IPS LCD (60Hz)",
    "CPU": "Kirin 710A",
    "numberOfCores": 8,
    "mainCamera": "48MP + 8MP + 2MP + 2MP",
    "frontCamera": "8MP",
    "battery": "5000mAh (22.5W wired)"
  },
  {
    "brand": "Huawei",
    "model": "Huawei Enjoy 20 Plus",
    "price": 299,
    "color": ["Space Silver", "Forest Green"],
    "storage": ["128GB"],
    "images": ["huawei/huawei91.webp", "huawei/huawei92.webp", "huawei/huawei93.webp", "huawei/huawei94.webp"],
    "category": "smartphones",
    "screen": "6.63-inch IPS LCD (60Hz)",
    "CPU": "Dimensity 720",
    "numberOfCores": 8,
    "mainCamera": "48MP + 8MP + 2MP",
    "frontCamera": "16MP",
    "battery": "4200mAh (40W wired)"
  },
  {
    "brand": "POCO",
    "model": "POCO X4 Pro 5G",
    "price": 299,
    "color": ["Laser Black", "Laser Blue"],
    "storage": ["64GB", "128GB"],
    "images": ["poco/poco1.webp", "poco/poco2.webp", "poco/poco3.webp", "poco/poco4.webp"],
    "category": "smartphones",
    "screen": "6.67-inch AMOLED (120Hz)",
    "CPU": "Snapdragon 695",
    "numberOfCores": 8,
    "mainCamera": "108MP + 8MP + 2MP",
    "frontCamera": "16MP",
    "battery": "5000mAh (67W wired)"
  },
  {
    "brand": "POCO",
    "model": "POCO F4 GT",
    "price": 599,
    "color": ["Stealth Black", "Knight Silver"],
    "storage": ["128GB", "256GB"],
    "images": ["poco/poco1.webp", "poco/poco2.webp", "poco/poco3.webp", "poco/poco4.webp"],
    "category": "smartphones",
    "screen": "6.67-inch AMOLED (120Hz)",
    "CPU": "Snapdragon 8 Gen 1",
    "numberOfCores": 8,
    "mainCamera": "64MP + 8MP + 2MP",
    "frontCamera": "20MP",
    "battery": "4700mAh (120W wired)"
  },
  {
    "brand": "POCO",
    "model": "POCO M4 Pro",
    "price": 199,
    "color": ["Power Black", "Cool Blue"],
    "storage": ["64GB", "128GB"],
    "images": ["poco/poco1.webp", "poco/poco2.webp", "poco/poco3.webp", "poco/poco4.webp"],
    "category": "smartphones",
    "screen": "6.43-inch AMOLED (90Hz)",
    "CPU": "Helio G96",
    "numberOfCores": 8,
    "mainCamera": "64MP + 8MP + 2MP",
    "frontCamera": "16MP",
    "battery": "5000mAh (33W wired)"
  },
  {
    "brand": "POCO",
    "model": "POCO C40",
    "price": 129,
    "color": ["Coral Green", "Poppy Orange"],
    "storage": ["32GB", "64GB"],
    "images": ["poco/poco1.webp", "poco/poco2.webp", "poco/poco3.webp", "poco/poco4.webp"],
    "category": "smartphones",
    "screen": "6.71-inch IPS LCD (60Hz)",
    "CPU": "JLQ JR510",
    "numberOfCores": 8,
    "mainCamera": "13MP + 2MP",
    "frontCamera": "5MP",
    "battery": "6000mAh (18W wired)"
  },
  {
    "brand": "POCO",
    "model": "POCO X5 Pro",
    "price": 349,
    "color": ["Horizon Blue", "Graphite Black"],
    "storage": ["128GB", "256GB"],
    "images": ["poco/poco1.webp", "poco/poco2.webp", "poco/poco3.webp", "poco/poco4.webp"],
    "category": "smartphones",
    "screen": "6.67-inch AMOLED (120Hz)",
    "CPU": "Snapdragon 778G",
    "numberOfCores": 8,
    "mainCamera": "108MP + 8MP + 2MP",
    "frontCamera": "16MP",
    "battery": "5000mAh (67W wired)"
  },
  {
    "brand": "Realme",
    "model": "Realme GT Neo 3",
    "price": 399,
    "color": ["Sprint White", "Nitro Blue"],
    "storage": ["128GB", "256GB"],
    "images": ["realme/realme1.webp", "realme/realme2.webp", "realme/realme3.webp", "realme/realme4.webp"],
    "category": "smartphones",
    "screen": "6.7-inch AMOLED (120Hz)",
    "CPU": "Dimensity 8100",
    "numberOfCores": 8,
    "mainCamera": "50MP + 8MP + 2MP",
    "frontCamera": "16MP",
    "battery": "5000mAh (80W wired)"
  },
  {
    "brand": "Realme",
    "model": "Realme 9 Pro+",
    "price": 349,
    "color": ["Aurora Green", "Midnight Black"],
    "storage": ["128GB", "256GB"],
    "images": ["realme/realme1.webp", "realme/realme2.webp", "realme/realme3.webp", "realme/realme4.webp"],
    "category": "smartphones",
    "screen": "6.4-inch AMOLED (90Hz)",
    "CPU": "Dimensity 920",
    "numberOfCores": 8,
    "mainCamera": "50MP + 8MP + 2MP",
    "frontCamera": "16MP",
    "battery": "4500mAh (60W wired)"
  },
  {
    "brand": "Realme",
    "model": "Realme C35",
    "price": 169,
    "color": ["Glowing Black", "Glowing Green"],
    "storage": ["64GB", "128GB"],
    "images": ["realme/realme1.webp", "realme/realme2.webp", "realme/realme3.webp", "realme/realme4.webp"],
    "category": "smartphones",
    "screen": "6.6-inch IPS LCD (60Hz)",
    "CPU": "Unisoc Tiger T616",
    "numberOfCores": 8,
    "mainCamera": "50MP + 2MP + 0.3MP",
    "frontCamera": "8MP",
    "battery": "5000mAh (18W wired)"
  },
  {
    "brand": "Realme",
    "model": "Realme 10 Pro+",
    "price": 379,
    "color": ["Hyperspace", "Dark Matter"],
    "storage": ["128GB", "256GB"],
    "images": ["realme/realme1.webp", "realme/realme2.webp", "realme/realme3.webp", "realme/realme4.webp"],
    "category": "smartphones",
    "screen": "6.7-inch AMOLED (120Hz)",
    "CPU": "Dimensity 1080",
    "numberOfCores": 8,
    "mainCamera": "108MP + 8MP + 2MP",
    "frontCamera": "16MP",
    "battery": "5000mAh (67W wired)"
  },
  {
    "brand": "Realme",
    "model": " Realme Narzo 50 Pro",
    "price": 249,
    "color": ["Hyper Blue", "Hyper Black"],
    "storage": ["64GB", "128GB"],
    "images": ["realme/realme1.webp", "realme/realme2.webp", "realme/realme3.webp", "realme/realme4.webp"],
    "category": "smartphones",
    "screen": "6.4-inch AMOLED (90Hz)",
    "CPU": "Dimensity 920",
    "numberOfCores": 8,
    "mainCamera": "48MP + 8MP + 2MP",
    "frontCamera": "16MP",
    "battery": "5000mAh (33W wired)"
  },
  {
    brand: "Apple",
    model: "Apple MacBook Pro 16-inch",
    images: ["apple1.webp", "apple2.webp", "apple3.webp", "apple4.webp"],
    colors: ["Space Gray", "Silver"],
    processor: "M2 Max",
    cores: 12,
    ram: "32GB",
    storage: ["512GB SSD", "1TB SSD", "2TB SSD", "4TB SSD", "8TB SSD"],
    battery: "100Wh (up to 21 hours)",
    screen: "16.2-inch (3456 × 2234)",
    category: "computers",
    price: 2499,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Apple",
    model: "Apple MacBook Air M2",
    images: ["apple3.webp", "apple2.webp", "apple1.webp", "apple4.webp"],
    colors: ["Midnight", "Starlight", "Space Gray", "Silver"],
    processor: "M2",
    cores: 8,
    ram: "16GB",
    storage: ["256GB SSD", "512GB SSD", "1TB SSD", "2TB SSD"],
    battery: "52.6Wh (up to 18 hours)",
    screen: "13.6-inch (2560 × 1664)",
    category: "computers",
    price: 1199,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Apple",
    model: "Apple iMac 24-inch",
    images: ["apple1.webp", "apple2.webp", "apple3.webp", "apple4.webp"],
    colors: ["Blue", "Green", "Pink", "Silver", "Yellow", "Orange", "Purple"],
    processor: "M1",
    cores: 8,
    ram: "16GB",
    storage: ["256GB SSD", "512GB SSD", "1TB SSD"],
    battery: "52.6Wh (up to 18 hours)",
    screen: "24-inch (4480 × 2520)",
    category: "computers",
    price: 1499,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Apple",
    model: "Apple Mac mini",
    images: ["apple3.webp", "apple2.webp", "apple1.webp", "apple4.webp"],
    colors: ["Silver"],
    processor: "M2 Pro",
    cores: 10,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD", "2TB SSD", "4TB SSD", "8TB SSD"],
    battery: "52.6Wh (up to 18 hours)",
    screen: "14-inch (1920 × 1200)",
    category: "computers",
    price: 1299,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Apple",
    model: "Apple Mac Studio",
    images: ["apple1.webp", "apple2.webp", "apple3.webp", "apple4.webp"],
    colors: ["Silver"],
    processor: "M2 Ultra",
    cores: 24,
    ram: "64GB",
    storage: ["1TB SSD", "2TB SSD", "4TB SSD", "8TB SSD"],
    battery: "52.6Wh (up to 18 hours)",
    screen: "14-inch (1920 × 1200)",
    category: "computers",
    price: 3999,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Lenovo",
    model: "Lenovo ThinkPad X1",
    images: ["lenovo1.webp", "lenovo2.webp", "lenovo3.webp", "lenovo4.webp"],
    colors: ["Black"],
    processor: "Intel i7-1260P",
    cores: 12,
    ram: "16GB",
    storage: ["256GB SSD", "512GB SSD", "1TB SSD", "2TB SSD"],
    battery: "57Wh (up to 15 hours)",
    screen: "14-inch (1920 × 1200)",
    category: "computers",
    price: 1699,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Lenovo",
    model: "Lenovo Yoga 9i",
    images: ["lenovo3.webp", "lenovo2.webp", "lenovo1.webp", "lenovo4.webp"],
    colors: ["Shadow Black", "Oatmeal"],
    processor: "Intel i7-1260P",
    cores: 12,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD"],
    battery: "75Wh (up to 14 hours)",
    screen: "14-inch (3840 × 2160)",
    category: "computers",
    price: 1499,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Lenovo",
    model: "Lenovo Legion 5 Pro",
    images: ["lenovo1.webp", "lenovo2.webp", "lenovo3.webp", "lenovo4.webp"],
    colors: ["Storm Gray"],
    processor: "AMD Ryzen 7 6800H",
    cores: 8,
    ram: "32GB",
    storage: ["512GB SSD", "1TB SSD", "2TB SSD"],
    battery: "80Wh (up to 8 hours)",
    screen: "16-inch (2560 × 1600)",
    category: "computers",
    price: 1599,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Lenovo",
    model: "Lenovo IdeaPad 5",
    images: ["lenovo3.webp", "lenovo2.webp", "lenovo1.webp", "lenovo4.webp"],
    colors: ["Cloud Grey", "Abyss Blue"],
    processor: "AMD Ryzen 5 5500U",
    cores: 6,
    ram: "8GB",
    storage: ["256GB SSD", "512GB SSD"],
    battery: "57Wh (up to 12 hours)",
    screen: "14-inch (1920 × 1080)",
    category: "computers",
    price: 699,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Lenovo",
    model: "Lenovo ThinkBook 14s Yoga",
    images: ["lenovo1.webp", "lenovo2.webp", "lenovo3.webp", "lenovo4.webp"],
    colors: ["Mineral Grey"],
    processor: "Intel i5-1235U",
    cores: 10,
    ram: "8GB",
    storage: ["256GB SSD", "512GB SSD"],
    battery: "60Wh (up to 10 hours)",
    screen: "14-inch (1920 × 1080)",
    category: "computers",
    price: 999,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Asus",
    model: "Asus ROG Zephyrus",
    images: ["asus1.webp", "asus2.webp", "asus3.webp", "asus4.webp"],
    colors: ["Moonlight White", "Eclipse Gray"],
    processor: "AMD Ryzen 9 6900HS",
    cores: 8,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD"],
    battery: "76Wh (up to 10 hours)",
    screen: "14-inch 2560 × 1440",
    category: "computers",
    price: 1599,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Asus",
    model: "Asus ZenBook 14",
    images: ["asus3.webp", "asus2.webp", "asus1.webp", "asus4.webp"],
    colors: ["Pine Grey", "Aqua Celadon"],
    processor: "Intel i7-1260P",
    cores: 12,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD"],
    battery: "75Wh (up to 15 hours)",
    screen: "14-inch (2880 × 1800)",
    category: "computers",
    price: 1199,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Asus",
    model: "Asus TUF Gaming F15",
    images: ["asus1.webp", "asus2.webp", "asus3.webp", "asus4.webp"],
    colors: ["Graphite Black", "Mecha Gray"],
    processor: "Intel i7-12700H",
    cores: 14,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD"],
    battery: "90Wh (up to 7 hours)",
    screen: "15.6-inch (1920 × 1080)",
    category: "computers",
    price: 1299,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Asus",
    model: "Asus VivoBook 15",
    images: ["asus3.webp", "asus2.webp", "asus1.webp", "asus4.webp"],
    colors: ["Indie Black", "Transparent Silver"],
    processor: "AMD Ryzen 5 5500U",
    cores: 6,
    ram: "8GB",
    storage: ["256GB SSD", "512GB SSD"],
    battery: "42Wh (up to 8 hours)",
    screen: "15.6-inch (1920 × 1080)",
    category: "computers",
    price: 599,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Asus",
    model: "Asus ExpertBook B9",
    images: ["asus1.webp", "asus2.webp", "asus3.webp", "asus4.webp"],
    colors: ["Star Black"],
    processor: "Intel i7-1260P",
    cores: 12,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD"],
    battery: "66Wh (up to 12 hours)",
    screen: "14-inch (1920 × 1080)",
    category: "computers",
    price: 1799,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Dell",
    model: "Dell XPS 13 Plus",
    images: ["dell1.webp", "dell2.webp", "dell3.webp", "dell4.webp"],
    colors: ["Platinum", "Graphite"],
    processor: "Intel i7-1260P",
    cores: 12,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD", "2TB SSD"],
    battery: "55Wh (up to 12 hours)",
    screen: "13.4-inch (1920 × 1200)",
    category: "computers",
    price: 1699,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Dell",
    model: "Dell Alienware x14",
    images: ["dell3.webp", "dell2.webp", "dell1.webp", "dell4.webp"],
    colors: ["Lunar Light", "Dark Side of the Moon"],
    processor: "Intel i7-12700H",
    cores: 14,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD", "2TB SSD"],
    battery: "80Wh (up to 8 hours)",
    screen: "14-inch (2560 × 1440)",
    category: "computers",
    price: 1999,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Dell",
    model: "Dell Inspiron 16 Plus",
    images: ["dell1.webp", "dell2.webp", "dell3.webp", "dell4.webp"],
    colors: ["Platinum Silver", "Dark Green"],
    processor: "Intel i7-1260P",
    cores: 12,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD"],
    battery: "86Wh (up to 10 hours)",
    screen: "16-inch  (3072 × 1920)",
    category: "computers",
    price: 1299,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Dell",
    model: "Dell Latitude 5430",
    images: ["dell3.webp", "dell2.webp", "dell1.webp", "dell4.webp"],
    colors: ["Gray"],
    processor: "Intel i5-1235U",
    cores: 10,
    ram: "8GB",
    storage: ["256GB SSD", "512GB SSD"],
    battery: "58Wh (up to 14 hours)",
    screen: "14-inch (1920 × 1080)",
    category: "computers",
    price: 1099,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Dell",
    model: "Dell G15 Gaming Laptop",
    images: ["dell1.webp", "dell2.webp", "dell3.webp", "dell4.webp"],
    colors: ["Dark Shadow Gray", "Specter Green"],
    processor: "AMD Ryzen 7 6800H",
    cores: 8,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD"],
    battery: "86Wh (up to 6 hours)",
    screen: "15.6-inch  (2560 × 1440)",
    category: "computers",
    price: 1199,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Acer",
    model: "Acer Swift 5",
    images: ["acer1.webp", "acer2.webp", "acer3.webp", "acer4.webp"],
    colors: ["Safari Gold", "Silver"],
    processor: "Intel i7-1260P",
    cores: 12,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD"],
    battery: "56Wh (up to 12 hours)",
    screen: "14-inch  (2560 × 1600) ",
    category: "computers",
    price: 1299,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Acer",
    model: " Acer Predator Helios 300",
    images: ["acer3.webp", "acer2.webp", "acer1.webp", "acer4.webp"],
    colors: ["Abyss Black"],
    processor: "Intel i7-12700H",
    cores: 14,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD"],
    battery: "90Wh (up to 5 hours)",
    screen: "15.6-inch (2560 × 1440)",
    category: "computers",
    price: 1499,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Acer",
    model: "Acer Aspire 5",
    images: ["acer1.webp", "acer2.webp", "acer3.webp", "acer4.webp"],
    colors: ["Pure Silver", "Charcoal Black"],
    processor: "AMD Ryzen 5 5500U",
    cores: 6,
    ram: "8GB",
    storage: ["256GB SSD", "512GB SSD"],
    battery: "48Wh (up to 8 hours)",
    screen: "15.6-inch (1920 × 1080)",
    category: "computers",
    price: 549,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Acer",
    model: "Acer Nitro 5",
    images: ["acer3.webp", "acer2.webp", "acer1.webp", "acer4.webp"],
    colors: ["Obsidian Black"],
    processor: "Intel i5-12500H",
    cores: 12,
    ram: "8GB",
    storage: ["256GB SSD", "512GB SSD", "1TB SSD"],
    battery: "57.5Wh (up to 6 hours)",
    screen: "15.6-inch (1920 × 1080)",
    category: "computers",
    price: 899,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "Acer",
    model: "Acer Spin 5",
    images: ["acer1.webp", "acer2.webp", "acer3.webp", "acer4.webp"],
    colors: ["Steel Gray"],
    processor: "Intel i7-1260P",
    cores: 12,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD"],
    battery: "56Wh (up to 10 hours)",
    screen: "14-inch (2560 × 1600)",
    category: "computers",
    price: 1199,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "HP",
    model: "HP Spectre x360 14",
    images: ["hp1.webp", "hp2.webp", "hp3.webp", "hp4.webp"],
    colors: ["Nightfall Black", "Nocturne Blue", "Natural Silver"],
    processor: "Intel i7-1260P",
    cores: 12,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD", "2TB SSD"],
    battery: "66Wh (up to 16 hours)",
    screen: "14-inch (3000 × 2000)",
    category: "computers",
    price: 1649,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "HP",
    model: "HP Envy 16",
    images: ["hp3.webp", "hp2.webp", "hp1.webp", "hp4.webp"],
    colors: ["Nightfall Black", "Natural Silver"],
    processor: "Intel i7-12700H",
    cores: 14,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD", "2TB SSD"],
    battery: "83Wh (up to 10 hours)",
    screen: "16-inch (3840 × 2400)",
    category: "computers",
    price: 1699,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "HP",
    model: "HP Pavilion 15",
    images: ["hp1.webp", "hp2.webp", "hp3.webp", "hp4.webp"],
    colors: ["Fog Blue", "Natural Silver", "Warm Gold"],
    processor: "AMD Ryzen 5 5500U",
    cores: 6,
    ram: "8GB",
    storage: ["256GB SSD", "512GB SSD"],
    battery: "52.5Wh (up to 8 hours)",
    screen: "15.6-inch (1920 × 1080)",
    category: "computers",
    price: 649,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "HP",
    model: "HP Omen 16",
    images: ["hp3.webp", "hp2.webp", "hp1.webp", "hp4.webp"],
    colors: ["Shadow Black"],
    processor: "AMD Ryzen 7 6800H",
    cores: 8,
    ram: "16GB",
    storage: ["512GB SSD", "1TB SSD"],
    battery: "83Wh (up to 7 hours)",
    screen: "16.1-inch (2560 × 1440)",
    category: "computers",
    price: 1399,
    mainCamera: "1080p FaceTime HD",
  },
  {
    brand: "HP",
    model: "HP EliteBook 840 G9",
    images: ["hp1.webp", "hp2.webp", "hp3.webp", "hp4.webp"],
    colors: ["Natural Silver", "Slate Blue"],
    processor: "Intel i5-1235U",
    cores: 10,
    ram: "8GB",
    storage: ["256GB SSD", "512GB SSD"],
    battery: "51Wh (up to 14 hours)",
    screen: "14-inch (1920 × 1080)",
    category: "computers",
    price: 1199,
    mainCamera: "1080p FaceTime HD",
  },
  {
    "brand": "Apple",
    "model": "Apple Watch Series 9",
    "price": 399,
    "color": ["Midnight", "Starlight", "Silver", "Red"],
    "storage": ["32GB"],
    "images": ["apple1.webp", "apple2.webp", "apple3.webp", "apple4.webp"],
    "category": "smartwatches",
    "screen": "1.9-inch Retina LTPO OLED",
    "CPU": "S9 SiP",
    "numberOfCores": 2,
    "battery": "308mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple Watch Ultra 2",
    "price": 799,
    "color": ["Titanium"],
    "storage": ["32GB"],
    "images": ["apple3.webp", "apple2.webp", "apple1.webp", "apple4.webp"],
    "category": "smartwatches",
    "screen": "2.1-inch Retina LTPO OLED",
    "CPU": "S9 SiP",
    "numberOfCores": 2,
    "battery": "542mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple Watch SE",
    "price": 249,
    "color": ["Silver", "Midnight", "Starlight"],
    "storage": ["32GB"],
    "images": ["apple1.webp", "apple2.webp", "apple3.webp", "apple4.webp"],
    "category": "smartwatches",
    "screen": "1.78-inch Retina LTPO OLED",
    "CPU": "S8 SiP",
    "numberOfCores": 2,
    "battery": "296mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple Watch Series 8",
    "price": 349,
    "color": ["Midnight", "Starlight", "Silver", "Gold"],
    "storage": ["32GB"],
    "images": ["apple3.webp", "apple2.webp", "apple1.webp", "apple4.webp"],
    "category": "smartwatches",
    "screen": "1.9-inch Retina LTPO OLED",
    "CPU": "S8 SiP",
    "numberOfCores": 2,
    "battery": "308mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple Watch Hermès",
    "price": 1299,
    "color": ["Noir", "Bleu", "Orange"],
    "storage": ["32GB"],
    "images": ["apple1.webp", "apple2.webp", "apple3.webp", "apple4.webp"],
    "category": "smartwatches",
    "screen": "1.9-inch Retina LTPO OLED",
    "CPU": "S9 SiP",
    "numberOfCores": 2,
    "battery": "308mAh"
  },
  {
    "brand": "Apple",
    "model": "Apple Watch Nike",
    "price": 399,
    "color": ["Black", "White", "Volt"],
    "storage": ["32GB"],
    "images": ["apple3.webp", "apple2.webp", "apple1.webp", "apple4.webp"],
    "category": "smartwatches",
    "screen": "1.9-inch Retina LTPO OLED",
    "CPU": "S9 SiP",
    "numberOfCores": 2,
    "battery": "308mAh"
  },

  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Watch6 Classic",
    "price": 369,
    "color": ["Black", "Silver"],
    "storage": ["16GB"],
    "images": ["samsung1.webp", "samsung2.webp", "samsung3.webp", "samsung4.webp"],
    "category": "smartwatches",
    "screen": "1.5-inch Super AMOLED",
    "CPU": "Exynos W930",
    "numberOfCores": 2,
    "battery": "425mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Watch6",
    "price": 299,
    "color": ["Graphite", "Gold", "Silver"],
    "storage": ["16GB"],
    "images": ["samsung3.webp", "samsung2.webp", "samsung1.webp", "samsung4.webp"],
    "category": "smartwatches",
    "screen": "1.3-inch Super AMOLED",
    "CPU": "Exynos W930",
    "numberOfCores": 2,
    "battery": "300mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Watch5 Pro",
    "price": 449,
    "color": ["Black", "Gray"],
    "storage": ["16GB"],
    "images": ["samsung1.webp", "samsung2.webp", "samsung3.webp", "samsung4.webp"],
    "category": "smartwatches",
    "screen": "1.4-inch Sapphire Crystal AMOLED",
    "CPU": "Exynos W920",
    "numberOfCores": 2,
    "battery": "590mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Watch5",
    "price": 279,
    "color": ["Sapphire", "Silver", "Pink Gold"],
    "storage": ["16GB"],
    "images": ["samsung3.webp", "samsung2.webp", "samsung1.webp", "samsung4.webp"],
    "category": "smartwatches",
    "screen": "1.2-inch Super AMOLED",
    "CPU": "Exynos W920",
    "numberOfCores": 2,
    "battery": "284mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Watch4 Classic",
    "price": 349,
    "color": ["Black", "Silver"],
    "storage": ["16GB"],
    "images": ["samsung1.webp", "samsung2.webp", "samsung3.webp", "samsung4.webp"],
    "category": "smartwatches",
    "screen": "1.4-inch Super AMOLED",
    "CPU": "Exynos W920",
    "numberOfCores": 2,
    "battery": "361mAh"
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Watch4",
    "price": 249,
    "color": ["Black", "Green", "Pink Gold"],
    "storage": ["16GB"],
    "images": ["samsung3.webp", "samsung2.webp", "samsung1.webp", "samsung4.webp"],
    "category": "smartwatches",
    "screen": "1.2-inch Super AMOLED",
    "CPU": "Exynos W920",
    "numberOfCores": 2,
    "battery": "247mAh"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi Watch S3",
    "price": 199,
    "color": ["Black", "Silver", "Gold"],
    "storage": ["4GB"],
    "images": ["xiaomi1.webp", "xiaomi2.webp", "xiaomi3.webp", "xiaomi4.webp"],
    "category": "smartwatches",
    "screen": "1.43-inch AMOLED",
    "CPU": "Snapdragon Wear 4100",
    "numberOfCores": 4,
    "battery": "500mAh"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi Watch 2 Pro",
    "price": 269,
    "color": ["Black", "Silver"],
    "storage": ["4GB"],
    "images": ["xiaomi3.webp", "xiaomi2.webp", "xiaomi1.webp", "xiaomi4.webp"],
    "category": "smartwatches",
    "screen": "1.43-inch AMOLED",
    "CPU": "Snapdragon W5+ Gen 1",
    "numberOfCores": 4,
    "battery": "495mAh"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi Watch 2",
    "price": 179,
    "color": ["Black", "Blue"],
    "storage": ["4GB"],
    "images": ["xiaomi1.webp", "xiaomi2.webp", "xiaomi3.webp", "xiaomi4.webp"],
    "category": "smartwatches",
    "screen": "1.43-inch AMOLED",
    "CPU": "Snapdragon W5 Gen 1",
    "numberOfCores": 4,
    "battery": "500mAh"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi Watch S1 Active",
    "price": 159,
    "color": ["Black", "Blue", "Orange"],
    "storage": ["2GB"],
    "images": ["xiaomi3.webp", "xiaomi2.webp", "xiaomi1.webp", "xiaomi4.webp"],
    "category": "smartwatches",
    "screen": "1.43-inch AMOLED",
    "CPU": "Snapdragon Wear 3100",
    "numberOfCores": 4,
    "battery": "470mAh"
  },
  {
    "brand": "Xiaomi",
    "model": "Xiaomi Watch S1",
    "price": 229,
    "color": ["Black", "Silver"],
    "storage": ["4GB"],
    "images": ["xiaomi1.webp", "xiaomi2.webp", "xiaomi3.webp", "xiaomi4.webp"],
    "category": "smartwatches",
    "screen": "1.43-inch AMOLED",
    "CPU": "Snapdragon Wear 4100",
    "numberOfCores": 4,
    "battery": "470mAh"
  },
  {
    "brand": "Xiaomi",
    "model": "Redmi Watch 3",
    "price": 99,
    "color": ["Black", "Ivory", "Blue"],
    "storage": ["2GB"],
    "images": ["xiaomi3.webp", "xiaomi2.webp", "xiaomi1.webp", "xiaomi4.webp"],
    "category": "smartwatches",
    "screen": "1.75-inch AMOLED",
    "CPU": "Unknown",
    "numberOfCores": 1,
    "battery": "289mAh"
  },
  {
    "brand": "Canon",
    "model": "Canon EOS R5",
    "price": 3899,
    "color": ["Black"],
    "storage": ["CFexpress, SD"],
    "images": ["canon3.webp", "canon2.webp", "canon1.webp", "canon4.webp"],
    "category": "cameras",
    "screen": "3.2-inch vari-angle LCD",
    "CPU": "DIGIC X",
    "sensor": "45MP Full-frame CMOS",
    "video": "8K 30p",
    "lensMount": "RF"
  },
  {
    "brand": "Canon",
    "model": "Canon EOS R6 Mark II",
    "price": 2499,
    "color": ["Black"],
    "storage": ["SD"],
    "images": ["canon1.webp", "canon2.webp", "canon3.webp", "canon4.webp"],
    "category": "cameras",
    "screen": "3-inch vari-angle LCD",
    "CPU": "DIGIC X",
    "sensor": "24MP Full-frame CMOS",
    "video": "4K 60p",
    "lensMount": "RF"
  },
  {
    "brand": "Canon",
    "model": "Canon EOS Rebel T8i",
    "price": 899,
    "color": ["Black"],
    "storage": ["SD"],
    "images": ["canon3.webp", "canon2.webp", "canon1.webp", "canon4.webp"],
    "category": "cameras",
    "screen": "3-inch vari-angle LCD",
    "CPU": "DIGIC 8",
    "sensor": "24MP APS-C CMOS",
    "video": "4K 24p",
    "lensMount": "EF-S"
  },
  {
    "brand": "Canon",
    "model": "Canon PowerShot G7 X Mark III",
    "price": 749,
    "color": ["Black", "Silver"],
    "storage": ["SD"],
    "images": ["canon1.webp", "canon2.webp", "canon3.webp", "canon4.webp"],
    "category": "cameras",
    "screen": "3-inch tilt LCD",
    "CPU": "DIGIC 8",
    "sensor": "20MP 1-inch CMOS",
    "video": "4K 30p",
    "lensMount": "Fixed"
  },
  {
    "brand": "Canon",
    "model": "Canon EOS 90D",
    "price": 1199,
    "color": ["Black"],
    "storage": ["SD"],
    "images": ["canon3.webp", "canon2.webp", "canon1.webp", "canon4.webp"],
    "category": "cameras",
    "screen": "3-inch vari-angle LCD",
    "CPU": "DIGIC 8",
    "sensor": "32MP APS-C CMOS",
    "video": "4K 30p",
    "lensMount": "EF-S"
  },
  {
    "brand": "Canon",
    "model": "Canon EOS M50 Mark II",
    "price": 599,
    "color": ["Black", "White"],
    "storage": ["SD"],
    "images": ["canon1.webp", "canon2.webp", "canon3.webp", "canon4.webp"],
    "category": "cameras",
    "screen": "3-inch vari-angle LCD",
    "CPU": "DIGIC 8",
    "sensor": "24MP APS-C CMOS",
    "video": "4K 24p",
    "lensMount": "EF-M"
  },
  {
    "brand": "Nikon",
    "model": "Nikon Z9",
    "price": 5499,
    "color": ["Black"],
    "storage": ["CFexpress"],
    "images": ["nikon3.webp", "nikon2.webp", "nikon1.webp", "nikon4.webp"],
    "category": "cameras",
    "screen": "3.2-inch quad-VGA LCD",
    "CPU": "Expeed 7",
    "sensor": "45MP Full-frame BSI CMOS",
    "video": "8K 30p",
    "lensMount": "Z"
  },
  {
    "brand": "Nikon",
    "model": "Nikon Z8",
    "price": 3999,
    "color": ["Black"],
    "storage": ["CFexpress, SD"],
    "images": ["nikon1.webp", "nikon2.webp", "nikon3.webp", "nikon4.webp"],
    "category": "cameras",
    "screen": "3.2-inch tilt LCD",
    "CPU": "Expeed 7",
    "sensor": "45MP Full-frame BSI CMOS",
    "video": "8K 30p",
    "lensMount": "Z"
  },
  {
    "brand": "Nikon",
    "model": "Nikon D850",
    "price": 2999,
    "color": ["Black"],
    "storage": ["XQD, SD"],
    "images": ["nikon3.webp", "nikon2.webp", "nikon1.webp", "nikon4.webp"],
    "category": "cameras",
    "screen": "3.2-inch tilt LCD",
    "CPU": "Expeed 5",
    "sensor": "45MP Full-frame CMOS",
    "video": "4K 30p",
    "lensMount": "F"
  },
  {
    "brand": "Nikon",
    "model": "Nikon Z6 II",
    "price": 1999,
    "color": ["Black"],
    "storage": ["CFexpress, SD"],
    "images": ["nikon1.webp", "nikon2.webp", "nikon3.webp", "nikon4.webp"],
    "category": "cameras",
    "screen": "3.2-inch tilt LCD",
    "CPU": "Dual Expeed 6",
    "sensor": "24MP Full-frame CMOS",
    "video": "4K 60p",
    "lensMount": "Z"
  },
  {
    "brand": "Nikon",
    "model": "Nikon Z50",
    "price": 859,
    "color": ["Black"],
    "storage": ["SD"],
    "images": ["nikon3.webp", "nikon2.webp", "nikon1.webp", "nikon4.webp"],
    "category": "cameras",
    "screen": "3.2-inch tilt LCD",
    "CPU": "Expeed 6",
    "sensor": "21MP APS-C CMOS",
    "video": "4K 30p",
    "lensMount": "Z"
  },
  {
    "brand": "Nikon",
    "model": "Nikon D3500",
    "price": 499,
    "color": ["Black"],
    "storage": ["SD"],
    "images": ["nikon1.webp", "nikon2.webp", "nikon3.webp", "nikon4.webp"],
    "category": "cameras",
    "screen": "3-inch fixed LCD",
    "CPU": "Expeed 4",
    "sensor": "24MP APS-C CMOS",
    "video": "1080p 60fps",
    "lensMount": "F"
  },
  {
    "brand": "Panasonic",
    "model": "Panasonic Lumix S1R",
    "price": 3699,
    "color": ["Black"],
    "storage": ["XQD, SD"],
    "images": ["panasonic1.webp", "panasonic2.webp", "panasonic3.webp", "panasonic4.webp"],
    "category": "cameras",
    "screen": "3.2-inch tilt LCD",
    "CPU": "Venus Engine",
    "sensor": "47MP Full-frame CMOS",
    "video": "4K 60p",
    "lensMount": "L"
  },
  {
    "brand": "Panasonic",
    "model": "Panasonic Lumix GH6",
    "price": 2199,
    "color": ["Black"],
    "storage": ["CFexpress, SD"],
    "images": ["panasonic3.webp", "panasonic2.webp", "panasonic1.webp", "panasonic4.webp"],
    "category": "cameras",
    "screen": "3-inch vari-angle LCD",
    "CPU": "Venus Engine",
    "sensor": "25MP Micro Four Thirds",
    "video": "5.7K 60p",
    "lensMount": "Micro Four Thirds"
  },
  {
    "brand": "Panasonic",
    "model": "Panasonic Lumix G9 II",
    "price": 1899,
    "color": ["Black"],
    "storage": ["SD"],
    "images": ["panasonic1.webp", "panasonic2.webp", "panasonic3.webp", "panasonic4.webp"],
    "category": "cameras",
    "screen": "3-inch vari-angle LCD",
    "CPU": "Venus Engine",
    "sensor": "25MP Micro Four Thirds",
    "video": "5.7K 30p",
    "lensMount": "Micro Four Thirds"
  },
  {
    "brand": "Panasonic",
    "model": "Panasonic Lumix S5 II",
    "price": 1999,
    "color": ["Black"],
    "storage": ["SD"],
    "images": ["panasonic3.webp", "panasonic2.webp", "panasonic1.webp", "panasonic4.webp"],
    "category": "cameras",
    "screen": "3-inch vari-angle LCD",
    "CPU": "Venus Engine",
    "sensor": "24MP Full-frame CMOS",
    "video": "6K 30p",
    "lensMount": "L"
  },
  {
    "brand": "Panasonic",
    "model": "Panasonic Lumix FZ1000 II",
    "price": 899,
    "color": ["Black"],
    "storage": ["SD"],
    "images": ["panasonic1.webp", "panasonic2.webp", "panasonic3.webp", "panasonic4.webp"],
    "category": "cameras",
    "screen": "3-inch vari-angle LCD",
    "CPU": "Venus Engine",
    "sensor": "20MP 1-inch CMOS",
    "video": "4K 30p",
    "lensMount": "Fixed"
  },
  {
    "brand": "Panasonic",
    "model": "Panasonic Lumix G100",
    "price": 749,
    "color": ["Black"],
    "storage": ["SD"],
    "images": ["panasonic3.webp", "panasonic2.webp", "panasonic1.webp", "panasonic4.webp"],
    "category": "cameras",
    "screen": "3-inch vari-angle LCD",
    "CPU": "Venus Engine",
    "sensor": "20MP Micro Four Thirds",
    "video": "4K 30p",
    "lensMount": "Micro Four Thirds"
  },
  {
    "brand": "Apple",
    "model": "Apple AirPods Max",
    "price": 549,
    "color": ["Space Gray", "Silver", "Sky Blue", "Green", "Pink"],
    "images": ["apple3.webp", "apple2.webp", "apple1.webp", "apple4.webp"],
    "category": "headphones",
    "type": "Over-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "20 hours",
    "bluetoothVersion": "5.0",
    "waterResistant": false
  },
  {
    "brand": "Apple",
    "model": "Apple AirPods Pro (2nd Gen)",
    "price": 249,
    "color": ["White"],
    "images": ["apple7.webp", "apple6.webp", "apple5.webp", "apple8.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "6 hours (30 with case)",
    "bluetoothVersion": "5.3",
    "waterResistant": true
  },
  {
    "brand": "Apple",
    "model": "Apple AirPods (3rd Gen)",
    "price": 169,
    "color": ["White"],
    "images": ["apple5.webp", "apple6.webp", "apple7.webp", "apple8.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": false,
    "battery": "6 hours (30 with case)",
    "bluetoothVersion": "5.0",
    "waterResistant": true
  },
  {
    "brand": "Apple",
    "model": "Apple Beats Studio Pro",
    "price": 349,
    "color": ["Black", "Deep Brown", "Navy", "Sandstone"],
    "images": ["apple1.webp", "apple2.webp", "apple3.webp", "apple4.webp"],
    "category": "headphones",
    "type": "Over-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "40 hours",
    "bluetoothVersion": "5.3",
    "waterResistant": false
  },
  {
    "brand": "Apple",
    "model": "Apple Beats Fit Pro",
    "price": 199,
    "color": ["Black", "White", "Gray", "Purple"],
    "images": ["apple3.webp", "apple2.webp", "apple1.webp", "apple4.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "6 hours (24 with case)",
    "bluetoothVersion": "5.3",
    "waterResistant": true
  },
  {
    "brand": "Apple",
    "model": "Apple Beats Solo3 Wireless",
    "price": 199,
    "color": ["Black", "White", "Red", "Blue"],
    "images": ["apple7.webp", "apple6.webp", "apple5.webp", "apple8.webp"],
    "category": "headphones",
    "type": "On-ear",
    "wireless": true,
    "noiseCancellation": false,
    "battery": "40 hours",
    "bluetoothVersion": "5.0",
    "waterResistant": false
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Buds2 Pro",
    "price": 229,
    "color": ["Graphite", "White", "Bora Purple"],
    "images": ["galaxy3.webp", "galaxy2.webp", "galaxy1.webp", "galaxy4.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "5 hours (18 with case)",
    "bluetoothVersion": "5.3",
    "waterResistant": true
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Buds FE",
    "price": 99,
    "color": ["Graphite", "White", "Lavender"],
    "images": ["galaxy1.webp", "galaxy2.webp", "galaxy3.webp", "galaxy4.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "6 hours (21 with case)",
    "bluetoothVersion": "5.2",
    "waterResistant": true
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Buds Live",
    "price": 149,
    "color": ["Mystic Bronze", "Mystic White", "Mystic Black"],
    "images": ["galaxy5.webp", "galaxy6.webp", "galaxy7.webp", "galax8.webp"],
    "category": "headphones",
    "type": "Open-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "6 hours (21 with case)",
    "bluetoothVersion": "5.0",
    "waterResistant": true
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Buds2",
    "price": 149,
    "color": ["Graphite", "White", "Olive", "Lavender"],
    "images": ["galaxy7.webp", "galaxy6.webp", "galaxy5.webp", "galaxy8.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "5 hours (20 with case)",
    "bluetoothVersion": "5.2",
    "waterResistant": true
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Buds Pro",
    "price": 199,
    "color": ["Phantom Black", "Phantom Silver", "Phantom Violet"],
    "images": ["galaxy3.webp", "galaxy2.webp", "galaxy1.webp", "galaxy4.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "5 hours (18 with case)",
    "bluetoothVersion": "5.0",
    "waterResistant": true
  },
  {
    "brand": "Samsung",
    "model": "Samsung Galaxy Buds+",
    "price": 129,
    "color": ["Black", "White", "Blue", "Red"],
    "images": ["galaxy5.webp", "galaxy6.webp", "galaxy7.webp", "galaxy8.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": false,
    "battery": "11 hours (22 with case)",
    "bluetoothVersion": "5.0",
    "waterResistant": true
  },
  {
    "brand": "JBL",
    "model": "JBL Tour Pro 2",
    "price": 249,
    "color": ["Black", "Gold"],
    "images": ["jbl3.webp", "jbl2.webp", "jbl1.webp", "jbl4.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "8 hours (30 with case)",
    "bluetoothVersion": "5.3",
    "waterResistant": true
  },
  {
    "brand": "JBL",
    "model": "JBL Live Pro 2",
    "price": 179,
    "color": ["Black", "White", "Beige", "Lilac"],
    "images": ["jbl1.webp", "jbl2.webp", "jbl3.webp", "jbl4.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "6 hours (30 with case)",
    "bluetoothVersion": "5.2",
    "waterResistant": true
  },
  {
    "brand": "JBL",
    "model": "JBL Quantum 910 Wireless",
    "price": 299,
    "color": ["Black"],
    "images": ["jbl5.webp", "jbl6.webp", "jbl7.webp", "jbl8.webp"],
    "category": "headphones",
    "type": "Over-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "39 hours",
    "bluetoothVersion": "5.2",
    "waterResistant": false
  },
  {
    "brand": "JBL",
    "model": "JBL Club One",
    "price": 349,
    "color": ["Black", "Silver"],
    "images": ["jbl7.webp", "jbl6.webp", "jbl5.webp", "jbl8.webp"],
    "category": "headphones",
    "type": "Over-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "45 hours",
    "bluetoothVersion": "5.0",
    "waterResistant": false
  },
  {
    "brand": "JBL",
    "model": "JBL Endurance Peak 3",
    "price": 99,
    "color": ["Black", "Blue", "Red"],
    "images": ["jbl3.webp", "jbl2.webp", "jbl1.webp", "jbl4.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": false,
    "battery": "10 hours (40 with case)",
    "bluetoothVersion": "5.2",
    "waterResistant": true
  },
  {
    "brand": "JBL",
    "model": "JBL Tune 760NC",
    "price": 129,
    "color": ["Black", "Blue", "White"],
    "images": ["jbl5.webp", "jbl6.webp", "jbl7.webp", "jbl8.webp"],
    "category": "headphones",
    "type": "Over-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "50 hours",
    "bluetoothVersion": "5.0",
    "waterResistant": false
  },
  {
    "brand": "Sony",
    "model": "Sony WH-1000XM5",
    "price": 399,
    "color": ["Black", "Silver", "Blue"],
    "images": ["sony1.webp", "sony2.webp", "sony3.webp", "sony4.webp"],
    "category": "headphones",
    "type": "Over-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "30 hours",
    "bluetoothVersion": "5.2",
    "waterResistant": false
  },
  {
    "brand": "Sony",
    "model": "Sony WF-1000XM5",
    "price": 299,
    "color": ["Black", "Silver"],
    "images": ["sony3.webp", "sony2.webp", "sony1.webp", "sony4.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "8 hours (24 with case)",
    "bluetoothVersion": "5.3",
    "waterResistant": true
  },
  {
    "brand": "Sony",
    "model": "Sony WH-XB910N",
    "price": 249,
    "color": ["Black", "Blue"],
    "images": ["sony5.webp", "sony6.webp", "sony7.webp", "sony8.webp"],
    "category": "headphones",
    "type": "Over-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "30 hours",
    "bluetoothVersion": "5.2",
    "waterResistant": false
  },
  {
    "brand": "Sony",
    "model": "Sony WF-C700N",
    "price": 119,
    "color": ["Black", "White", "Lavender", "Sage Green"],
    "images": ["sony7.webp", "sony6.webp", "sony5.webp", "sony8.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "7.5 hours (20 with case)",
    "bluetoothVersion": "5.2",
    "waterResistant": true
  },
  {
    "brand": "Sony",
    "model": "Sony WH-CH720N",
    "price": 149,
    "color": ["Black", "White", "Blue"],
    "images": ["sony1.webp", "sony2.webp", "sony3.webp", "sony4.webp"],
    "category": "headphones",
    "type": "Over-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "35 hours",
    "bluetoothVersion": "5.2",
    "waterResistant": false
  },
  {
    "brand": "Sony",
    "model": "Sony LinkBuds S",
    "price": 199,
    "color": ["Black", "White", "Ecru"],
    "images": ["sony5.webp", "sony6.webp", "sony7.webp", "sony8.webp"],
    "category": "headphones",
    "type": "In-ear",
    "wireless": true,
    "noiseCancellation": true,
    "battery": "6 hours (20 with case)",
    "bluetoothVersion": "5.2",
    "waterResistant": true
  }
];
